export const products = [
  {
    id: 1,
    title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    price: 109.95,
    description:
      "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "men's clothing",
    image: "https://picsum.photos/id/1011/600/600",
    rating: { rate: 3.9, count: 120 },
  },
  {
    id: 2,
    title: "Mens Casual Premium Slim Fit T-Shirts ",
    price: 22.3,
    description: "Slim-fitting style, contrast raglan long sleeve...",
    category: "men's clothing",
    image: "https://picsum.photos/id/1015/600/600",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    price: 55.99,
    description: "great outerwear jackets for Spring/Autumn/Winter...",
    category: "men's clothing",
    image: "https://picsum.photos/id/1025/600/600",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 4,
    title: "Mens Casual Slim Fit",
    price: 15.99,
    description: "The color could be slightly different between on the screen...",
    category: "men's clothing",
    image: "https://picsum.photos/id/1035/600/600",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 5,
    title:
      "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: 695,
    description: "From our Legends Collection...",
    category: "jewelery",
    image: "https://picsum.photos/id/1040/600/600",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 6,
    title: "Solid Gold Petite Micropave ",
    price: 168,
    description:
      "Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    category: "jewelery",
    image: "https://picsum.photos/id/1050/600/600",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 7,
    title: "White Gold Plated Princess",
    price: 9.99,
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her.",
    category: "jewelery",
    image: "https://picsum.photos/id/1060/600/600",
    rating: { rate: 3, count: 400 },
  },
  {
    id: 8,
    title: "Pierced Owl Rose Gold Plated Stainless Steel Double",
    price: 10.99,
    description:
      "Rose Gold Plated Double Flared Tunnel Plug Earrings.",
    category: "jewelery",
    image: "https://picsum.photos/id/1070/600/600",
    rating: { rate: 1.9, count: 100 },
  },
  {
    id: 9,
    title: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
    price: 64,
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers...",
    category: "electronics",
    image: "https://picsum.photos/id/1080/600/600",
    rating: { rate: 3.3, count: 203 },
  },
  {
    id: 10,
    title: "SanDisk SSD PLUS 1TB Internal SSD",
    price: 109,
    description: "Easy upgrade for faster boot up...",
    category: "electronics",
    image: "https://picsum.photos/id/1084/600/600",
    rating: { rate: 2.9, count: 470 },
  },
  {
    id: 11,
    title: "Silicon Power 256GB SSD",
    price: 109,
    description:
      "3D NAND flash are applied to deliver high transfer speeds...",
    category: "electronics",
    image: "https://picsum.photos/id/1081/600/600",
    rating: { rate: 4.8, count: 319 },
  },
  {
    id: 12,
    title: "WD 4TB Gaming Drive Works with Playstation 4",
    price: 114,
    description: "Expand your PS4 gaming experience...",
    category: "electronics",
    image: "https://picsum.photos/id/1082/600/600",
    rating: { rate: 4.8, count: 400 },
  },
  {
    id: 13,
    title: "Acer SB220Q 21.5 inches Full HD Monitor",
    price: 599,
    description: "21.5 inches Full HD IPS display...",
    category: "electronics",
    image: "https://picsum.photos/id/1083/600/600",
    rating: { rate: 2.9, count: 250 },
  },
  {
    id: 14,
    title: "Samsung 49-Inch Curved Gaming Monitor",
    price: 999.99,
    description:
      "49 INCH SUPER ULTRAWIDE CURVED GAMING MONITOR...",
    category: "electronics",
    image: "https://picsum.photos/id/237/600/600",
    rating: { rate: 2.2, count: 140 },
  },
  {
    id: 15,
    title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket",
    price: 56.99,
    description: "Detachable liner fabric...",
    category: "women's clothing",
    image: "https://picsum.photos/id/238/600/600",
    rating: { rate: 2.6, count: 235 },
  },
  {
    id: 16,
    title: "Lock and Love Women's Faux Leather Jacket",
    price: 29.95,
    description:
      "Faux leather material for style and comfort...",
    category: "women's clothing",
    image: "https://picsum.photos/id/239/600/600",
    rating: { rate: 2.9, count: 340 },
  },
  {
    id: 17,
    title: "Rain Jacket Women Windbreaker",
    price: 39.99,
    description:
      "Lightweight perfect for trip or casual wear...",
    category: "women's clothing",
    image: "https://picsum.photos/id/240/600/600",
    rating: { rate: 3.8, count: 679 },
  },
  {
    id: 18,
    title: "MBJ Women's Solid Short Sleeve Boat Neck",
    price: 9.85,
    description:
      "Lightweight fabric with great stretch...",
    category: "women's clothing",
    image: "https://picsum.photos/id/241/600/600",
    rating: { rate: 4.7, count: 130 },
  },
  {
    id: 19,
    title: "Opna Women's Short Sleeve Moisture",
    price: 7.95,
    description:
      "Lightweight, roomy and highly breathable...",
    category: "women's clothing",
    image: "https://picsum.photos/id/242/600/600",
    rating: { rate: 4.5, count: 146 },
  },
  {
    id: 20,
    title: "DANVOUY Womens T Shirt Casual Cotton Short",
    price: 12.99,
    description:
      "Casual short sleeve fashion tees...",
    category: "women's clothing",
    image: "https://picsum.photos/id/243/600/600",
    rating: { rate: 3.6, count: 145 },
  },
];
